# Generated by Django 6.1.2 on 2026-10-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedules', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'installment_number'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'installment_number'), name='unique_installment_per_loan')],
            },
        ),
    ]
