# Generated by Django 6.1.2 on 2026-10-09 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_reference', models.CharField(max_length=40, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_reference', models.CharField(max_length=50)),
                ('deposited_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_SETTLEMENT', 'Pending Settlement'), ('SETTLED', 'Settled'), ('SETTLED_WITH_DISCREPANCY', 'Settled with Discrepancy'), ('FAILED', 'Failed')], default='PENDING_SETTLEMENT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_deposits', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
