# Generated by Django 6.1.2 on 2026-10-09 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_reference_number', models.CharField(max_length=100, unique=True)),
                ('credited_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='treasury.bankdeposit')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_bank_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
