# Generated by Django 6.1.2 on 2026-10-09 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='branches.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
