# Generated by Django 6.1.2 on 2026-10-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
        ('repayments', '0002_repaymentallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_links', to='repayments.paymentreceipt')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_links', to='reconciliation.cashsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'receipt'), name='unique_receipt_per_submission')],
            },
        ),
    ]
