# Generated by Django 6.1.2 on 2026-10-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_repaymentschedule'),
        ('repayments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('PENALTY', 'Penalty'), ('OVERDUE_INTEREST', 'Overdue Interest'), ('PRINCIPAL', 'Principal'), ('INTEREST', 'Interest'), ('ADVANCE', 'Advance Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='repayments.paymentreceipt')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='loans.repaymentschedule')),
            ],
        ),
    ]
